export const DESCRIPTIONS_CATALOG = [
  "¿Buscas un hogar que combine elegancia y confort? Esta espectacular {tipo} en {direccion} es exactamente lo que mereces. Con {m2_construccion}m2 de construcción exquisitamente distribuidos, incluye {recamaras} recámaras y {banos} baños, ofreciendo el espacio perfecto para tu familia. Cada rincón ha sido pensado para brindar tranquilidad y un nivel de vida premium.",
  "Haz realidad el sueño de vivir donde siempre imaginaste. Esta increíble {tipo} te recibe con una distribución inteligente que inunda cada espacio de luz natural. Disfruta de sus {recamaras} acogedoras habitaciones y {banos} baños en un entorno seguro y con alta plusvalía en {direccion}. Una inversión inteligente que te enamorará desde el primer instante.",
  "Una oportunidad única en el mercado. En el corazón de la zona con mayor crecimiento, se encuentra esta exclusiva {tipo}. Sus {m2_construccion}m2 de construcción ofrecen comodidad inigualable. Imagina despertar en una de sus {recamaras} habitaciones, rodeado de acabados de primer nivel y la paz que solo {direccion} puede ofrecer. Listo para que escribas tu próxima historia.",
  "El refugio perfecto lejos del ruido, pero cerca de todo. Te presentamos esta imponente {tipo} que redefine el buen gusto. Cuenta con {recamaras} amplias recámaras, {banos} baños de lujo y una armonía arquitectónica insuperable. Ubicada estratégicamente en {direccion}, es más que una propiedad; es el estilo de vida que siempre buscaste.",
  "Diseño, amplitud y exclusividad definen esta majestuosa {tipo}. Cada uno de sus {m2_construccion}m2 ha sido optimizado para regalarte momentos inolvidables. Con {recamaras} recámaras diseñadas para el máximo descanso y {banos} baños impecables, esta joya arquitectónica en {direccion} es la respuesta a tus más altas exigencias.",
  "Déjate conquistar por esta fascinante {tipo} ubicada en una zona de inmejorable plusvalía. Sus espacios abiertos y excelente iluminación resaltan sus {m2_construccion}m2 de construcción. Disfruta del máximo confort en sus {recamaras} recámaras y {banos} baños. No dejes pasar la oportunidad de llamar a este lugar tu hogar.",
  "Vivir con estilo nunca fue tan fácil. Esta maravillosa {tipo} en {direccion} lo tiene todo: modernidad, seguridad y confort. Con espacios generosos que incluyen {recamaras} recámaras y {banos} baños, está lista para recibir a sus nuevos dueños. Su excelente estado de conservación la convierte en la opción ideal del mercado actual."
];
